//George Koutsogiannakis
package Client.Services.Enums;
public enum Jobs{ELECTRICAL_ENGINEER,MECHANICAL_ENGINEER,ADMINISTRATIVE_SECRETARY,ADMINISTRATIVE_ASSISTANT,ENGINEERING_MANAGER,ADMINISTRATIVE_MANAGER,NONE};
